spring:
  redis:
    host: 124.71.128.96
    port: 6379
    password: xujialin
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall
    username: root
    password: xujialin
  rabbitmq:
    host: 39.101.178.126
    virtual-host: /
    port: 5672
    username: xujialin
    password: xujialin

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xujialin.mapper
server:
  port: 8081